//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Spatial.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SpatialDBEntities : DbContext
    {
        public SpatialDBEntities()
            : base("name=SpatialDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_location> tbl_location { get; set; }
        public virtual DbSet<tbl_School> tbl_School { get; set; }
    
        public virtual ObjectResult<string> SearchGeoLocation_sp(System.Data.Entity.Spatial.DbGeography p_polygon)
        {
            var p_polygonParameter = p_polygon != null ?
                new ObjectParameter("p_polygon", p_polygon) :
                new ObjectParameter("p_polygon", typeof(System.Data.Entity.Spatial.DbGeography));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SearchGeoLocation_sp", p_polygonParameter);
        }
    }
}
