//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Spatial.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_School
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    }
}
